-- Remove all "product has no checklist" OP notifications previously generated by the nightly cron.
-- The `type` + `owner_type` pair uniquely identifies them; no other notification source uses this combo.
-- Run once after deploying the product-save hook that replaces the cron scan.

DELETE FROM notification
WHERE type = 'product_no_checklist'
  AND owner_type = 'product';
