DROP TABLE IF EXISTS `ghl_processed_leads`;

CREATE TABLE IF NOT EXISTS `ghl_processed_leads` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `conversation_id` VARCHAR(100) NOT NULL,
  `contact_id` VARCHAR(100) NULL DEFAULT NULL,
  `assigned_to_user_id` VARCHAR(100) NULL DEFAULT NULL,
  `lead_started_at` DATETIME NOT NULL,
  `lead_ended_at` DATETIME NULL DEFAULT NULL,
  `first_customer_message_id` VARCHAR(100) NOT NULL,
  `tracked_message_count` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `responded_message_count` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `avg_first_5_response_seconds` INT NULL DEFAULT NULL,
  `response_1_customer_message_id` VARCHAR(100) NULL DEFAULT NULL,
  `response_1_customer_message_at` DATETIME NULL DEFAULT NULL,
  `response_1_agent_message_id` VARCHAR(100) NULL DEFAULT NULL,
  `response_1_agent_message_at` DATETIME NULL DEFAULT NULL,
  `response_1_seconds` INT NULL DEFAULT NULL,
  `response_2_customer_message_id` VARCHAR(100) NULL DEFAULT NULL,
  `response_2_customer_message_at` DATETIME NULL DEFAULT NULL,
  `response_2_agent_message_id` VARCHAR(100) NULL DEFAULT NULL,
  `response_2_agent_message_at` DATETIME NULL DEFAULT NULL,
  `response_2_seconds` INT NULL DEFAULT NULL,
  `response_3_customer_message_id` VARCHAR(100) NULL DEFAULT NULL,
  `response_3_customer_message_at` DATETIME NULL DEFAULT NULL,
  `response_3_agent_message_id` VARCHAR(100) NULL DEFAULT NULL,
  `response_3_agent_message_at` DATETIME NULL DEFAULT NULL,
  `response_3_seconds` INT NULL DEFAULT NULL,
  `response_4_customer_message_id` VARCHAR(100) NULL DEFAULT NULL,
  `response_4_customer_message_at` DATETIME NULL DEFAULT NULL,
  `response_4_agent_message_id` VARCHAR(100) NULL DEFAULT NULL,
  `response_4_agent_message_at` DATETIME NULL DEFAULT NULL,
  `response_4_seconds` INT NULL DEFAULT NULL,
  `response_5_customer_message_id` VARCHAR(100) NULL DEFAULT NULL,
  `response_5_customer_message_at` DATETIME NULL DEFAULT NULL,
  `response_5_agent_message_id` VARCHAR(100) NULL DEFAULT NULL,
  `response_5_agent_message_at` DATETIME NULL DEFAULT NULL,
  `response_5_seconds` INT NULL DEFAULT NULL,
  `is_converted` TINYINT(1) NOT NULL DEFAULT 0,
  `booking_id` INT(11) NULL DEFAULT NULL,
  `converted_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_conversation_lead` (`conversation_id`, `lead_started_at`, `first_customer_message_id`),
  KEY `idx_conversation_started_at` (`conversation_id`, `lead_started_at`),
  KEY `idx_contact_started_at` (`contact_id`, `lead_started_at`),
  KEY `idx_assigned_to_user_id` (`assigned_to_user_id`),
  KEY `idx_conversion_status` (`is_converted`, `converted_at`),
  KEY `idx_booking_id` (`booking_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
