-- Step 1: Add new ENUM values (keep old one temporarily)
ALTER TABLE payment
  MODIFY COLUMN Type ENUM(
    'ADDITIONAL PAYMENT','AGENT COMMISSION','AGENT COMMISSION FROM SUPPLIER',
    'BANK CHARGES','CUSTOMER REFUND','CREDIT CARD CHARGES','DEPOSIT','FULL',
    'ONE-TIME PAYMENT','SUPPLIER PAYMENT','SUPPLIER PAYMENT (DEPOSIT)',
    'SUPPLIER PAYMENT (FULL)','SUPPLIER PAYMENT (ADDITIONAL)','SUPPLIER REFUND'
  ) NULL;

-- Step 2: Migrate existing data
UPDATE payment SET Type = 'SUPPLIER PAYMENT (FULL)' WHERE Type = 'SUPPLIER PAYMENT';

-- Step 3: Remove old ENUM value
ALTER TABLE payment
  MODIFY COLUMN Type ENUM(
    'ADDITIONAL PAYMENT','AGENT COMMISSION','AGENT COMMISSION FROM SUPPLIER',
    'BANK CHARGES','CUSTOMER REFUND','CREDIT CARD CHARGES','DEPOSIT','FULL',
    'ONE-TIME PAYMENT','SUPPLIER PAYMENT (DEPOSIT)','SUPPLIER PAYMENT (FULL)',
    'SUPPLIER PAYMENT (ADDITIONAL)','SUPPLIER REFUND'
  ) NULL;
