CREATE TABLE IF NOT EXISTS `ghl_sync_run_log` (
  `LogID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RunID` VARCHAR(64) NOT NULL,
  `SyncKey` VARCHAR(120) NOT NULL,
  `LogType` VARCHAR(40) NOT NULL,
  `Message` TEXT NULL,
  `Page` INT NULL DEFAULT NULL,
  `PulledCount` INT NOT NULL DEFAULT 0,
  `InsertedCount` INT NOT NULL DEFAULT 0,
  `HttpStatus` INT NULL DEFAULT NULL,
  `Meta` LONGTEXT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`LogID`),
  KEY `idx_runid_created` (`RunID`, `CreatedAt`),
  KEY `idx_logtype_created` (`LogType`, `CreatedAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ghl_conversations` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RunID` VARCHAR(64) NOT NULL,
  `ConversationID` VARCHAR(100) NULL DEFAULT NULL,
  `LocationID` VARCHAR(100) NOT NULL,
  `DateAdded` DATETIME NULL DEFAULT NULL,
  `DateUpdated` DATETIME NULL DEFAULT NULL,
  `LastMessageDate` DATETIME NULL DEFAULT NULL,
  `LastInboundWhatsappMessageDate` DATETIME NULL DEFAULT NULL,
  `LastMessageType` VARCHAR(100) NULL DEFAULT NULL,
  `LastMessageBody` TEXT NULL,
  `LastMessageDirection` VARCHAR(40) NULL DEFAULT NULL,
  `Inbox` TINYINT(1) NOT NULL DEFAULT 0,
  `UnreadCount` INT NOT NULL DEFAULT 0,
  `AssignedTo` VARCHAR(100) NULL DEFAULT NULL,
  `LastManualMessageDate` DATETIME NULL DEFAULT NULL,
  `Followers` LONGTEXT NULL,
  `IsLastMessageInternalComment` TINYINT(1) NOT NULL DEFAULT 0,
  `ContactID` VARCHAR(100) NULL DEFAULT NULL,
  `FullName` VARCHAR(255) NULL DEFAULT NULL,
  `ContactName` VARCHAR(255) NULL DEFAULT NULL,
  `CompanyName` VARCHAR(255) NULL DEFAULT NULL,
  `Phone` VARCHAR(50) NULL DEFAULT NULL,
  `Tags` LONGTEXT NULL,
  `Type` VARCHAR(100) NULL DEFAULT NULL,
  `Scoring` LONGTEXT NULL,
  `Attributed` LONGTEXT NULL,
  `Sort` LONGTEXT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `idx_runid` (`RunID`),
  KEY `idx_location` (`LocationID`),
  KEY `idx_conversation_id` (`ConversationID`),
  KEY `idx_last_message_date` (`LastMessageDate`),
  KEY `idx_contact_id` (`ContactID`),
  KEY `idx_date_updated` (`DateUpdated`),
  KEY `idx_last_inbound_wa_date` (`LastInboundWhatsappMessageDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
