-- GHL (GoHighLevel) conversations sync table
-- Stores conversations fetched from GET https://services.leadconnectorhq.com/conversations/search

CREATE TABLE IF NOT EXISTS `ghl_conversations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `conversation_id` VARCHAR(100) NOT NULL COMMENT 'GHL conversation id',
  `location_id` VARCHAR(100) NULL DEFAULT NULL,
  `contact_id` VARCHAR(100) NULL DEFAULT NULL,
  `assigned_to` VARCHAR(100) NULL DEFAULT NULL COMMENT 'GHL user id',
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `contact_name` VARCHAR(255) NULL DEFAULT NULL,
  `company_name` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `conversation_type` VARCHAR(100) NULL DEFAULT NULL,
  `inbox` TINYINT(1) NOT NULL DEFAULT 0,
  `unread_count` INT NOT NULL DEFAULT 0,
  `last_message_type` VARCHAR(100) NULL DEFAULT NULL,
  `last_message_body` TEXT NULL,
  `last_message_direction` VARCHAR(50) NULL DEFAULT NULL,
  `last_outbound_message_action` VARCHAR(100) NULL DEFAULT NULL,
  `last_internal_comment` TEXT NULL,
  `is_last_message_internal_comment` TINYINT(1) NOT NULL DEFAULT 0,
  `date_added` DATETIME NULL DEFAULT NULL,
  `date_updated` DATETIME NULL DEFAULT NULL,
  `last_message_date` DATETIME NULL DEFAULT NULL,
  `last_inbound_whatsapp_message_date` DATETIME NULL DEFAULT NULL,
  `last_manual_message_date` DATETIME NULL DEFAULT NULL,
  `followers_json` JSON NULL,
  `mentions_json` JSON NULL,
  `tags_json` JSON NULL,
  `scoring_json` JSON NULL,
  `sort_json` JSON NULL,
  `attributed_json` JSON NULL,
  `raw_json` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_conversation_id` (`conversation_id`),
  KEY `idx_location_id` (`location_id`),
  KEY `idx_contact_id` (`contact_id`),
  KEY `idx_assigned_to` (`assigned_to`),
  KEY `idx_last_message_date` (`last_message_date`),
  KEY `idx_date_updated` (`date_updated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
