ALTER TABLE payment
  MODIFY COLUMN Type ENUM(
    'ADDITIONAL PAYMENT','AGENT COMMISSION','AGENT COMMISSION FROM SUPPLIER',
    'BANK CHARGES','CUSTOMER REFUND','CREDIT CARD CHARGES','DEPOSIT','FULL',
    'ONE-TIME PAYMENT','SUPPLIER PAYMENT','SUPPLIER REFUND'
  ) NULL;
