ALTER TABLE `ghl_processed_leads`
  ADD COLUMN `recent_tracked_message_count` TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER `avg_first_5_response_seconds`,
  ADD COLUMN `recent_responded_message_count` TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER `recent_tracked_message_count`,
  ADD COLUMN `avg_recent_5_response_seconds` INT NULL DEFAULT NULL AFTER `recent_responded_message_count`,
  ADD COLUMN `recent_response_1_customer_message_id` VARCHAR(100) NULL DEFAULT NULL AFTER `response_5_seconds`,
  ADD COLUMN `recent_response_1_customer_message_at` DATETIME NULL DEFAULT NULL AFTER `recent_response_1_customer_message_id`,
  ADD COLUMN `recent_response_1_agent_message_id` VARCHAR(100) NULL DEFAULT NULL AFTER `recent_response_1_customer_message_at`,
  ADD COLUMN `recent_response_1_agent_message_at` DATETIME NULL DEFAULT NULL AFTER `recent_response_1_agent_message_id`,
  ADD COLUMN `recent_response_1_seconds` INT NULL DEFAULT NULL AFTER `recent_response_1_agent_message_at`,
  ADD COLUMN `recent_response_2_customer_message_id` VARCHAR(100) NULL DEFAULT NULL AFTER `recent_response_1_seconds`,
  ADD COLUMN `recent_response_2_customer_message_at` DATETIME NULL DEFAULT NULL AFTER `recent_response_2_customer_message_id`,
  ADD COLUMN `recent_response_2_agent_message_id` VARCHAR(100) NULL DEFAULT NULL AFTER `recent_response_2_customer_message_at`,
  ADD COLUMN `recent_response_2_agent_message_at` DATETIME NULL DEFAULT NULL AFTER `recent_response_2_agent_message_id`,
  ADD COLUMN `recent_response_2_seconds` INT NULL DEFAULT NULL AFTER `recent_response_2_agent_message_at`,
  ADD COLUMN `recent_response_3_customer_message_id` VARCHAR(100) NULL DEFAULT NULL AFTER `recent_response_2_seconds`,
  ADD COLUMN `recent_response_3_customer_message_at` DATETIME NULL DEFAULT NULL AFTER `recent_response_3_customer_message_id`,
  ADD COLUMN `recent_response_3_agent_message_id` VARCHAR(100) NULL DEFAULT NULL AFTER `recent_response_3_customer_message_at`,
  ADD COLUMN `recent_response_3_agent_message_at` DATETIME NULL DEFAULT NULL AFTER `recent_response_3_agent_message_id`,
  ADD COLUMN `recent_response_3_seconds` INT NULL DEFAULT NULL AFTER `recent_response_3_agent_message_at`,
  ADD COLUMN `recent_response_4_customer_message_id` VARCHAR(100) NULL DEFAULT NULL AFTER `recent_response_3_seconds`,
  ADD COLUMN `recent_response_4_customer_message_at` DATETIME NULL DEFAULT NULL AFTER `recent_response_4_customer_message_id`,
  ADD COLUMN `recent_response_4_agent_message_id` VARCHAR(100) NULL DEFAULT NULL AFTER `recent_response_4_customer_message_at`,
  ADD COLUMN `recent_response_4_agent_message_at` DATETIME NULL DEFAULT NULL AFTER `recent_response_4_agent_message_id`,
  ADD COLUMN `recent_response_4_seconds` INT NULL DEFAULT NULL AFTER `recent_response_4_agent_message_at`,
  ADD COLUMN `recent_response_5_customer_message_id` VARCHAR(100) NULL DEFAULT NULL AFTER `recent_response_4_seconds`,
  ADD COLUMN `recent_response_5_customer_message_at` DATETIME NULL DEFAULT NULL AFTER `recent_response_5_customer_message_id`,
  ADD COLUMN `recent_response_5_agent_message_id` VARCHAR(100) NULL DEFAULT NULL AFTER `recent_response_5_customer_message_at`,
  ADD COLUMN `recent_response_5_agent_message_at` DATETIME NULL DEFAULT NULL AFTER `recent_response_5_agent_message_id`,
  ADD COLUMN `recent_response_5_seconds` INT NULL DEFAULT NULL AFTER `recent_response_5_agent_message_at`;
