ALTER TABLE `ghl_contacts`
  ADD COLUMN `location_id`             VARCHAR(100) NULL DEFAULT NULL AFTER `contact_id`,
  ADD COLUMN `contact_name`            VARCHAR(255) NULL DEFAULT NULL AFTER `location_id`,
  ADD COLUMN `first_name_raw`          VARCHAR(255) NULL DEFAULT NULL AFTER `last_name`,
  ADD COLUMN `last_name_raw`           VARCHAR(255) NULL DEFAULT NULL AFTER `first_name_raw`,
  ADD COLUMN `company_name`            VARCHAR(255) NULL DEFAULT NULL AFTER `last_name_raw`,
  ADD COLUMN `business_id`             VARCHAR(100) NULL DEFAULT NULL AFTER `company_name`,
  ADD COLUMN `contact_type`            VARCHAR(50) NULL DEFAULT NULL AFTER `business_id`,
  ADD COLUMN `source`                  VARCHAR(255) NULL DEFAULT NULL AFTER `contact_type`,
  ADD COLUMN `dnd`                     TINYINT(1) NOT NULL DEFAULT 0 AFTER `source`,
  ADD COLUMN `dnd_settings_json`       JSON NULL AFTER `dnd`,
  ADD COLUMN `city`                    VARCHAR(100) NULL DEFAULT NULL AFTER `dnd_settings_json`,
  ADD COLUMN `state`                   VARCHAR(100) NULL DEFAULT NULL AFTER `city`,
  ADD COLUMN `postal_code`             VARCHAR(50) NULL DEFAULT NULL AFTER `state`,
  ADD COLUMN `address1`                VARCHAR(500) NULL DEFAULT NULL AFTER `postal_code`,
  ADD COLUMN `country`                 VARCHAR(10) NULL DEFAULT NULL AFTER `address1`,
  ADD COLUMN `website`                 VARCHAR(500) NULL DEFAULT NULL AFTER `country`,
  ADD COLUMN `timezone`                VARCHAR(100) NULL DEFAULT NULL AFTER `website`,
  ADD COLUMN `profile_photo`           VARCHAR(1000) NULL DEFAULT NULL AFTER `timezone`,
  ADD COLUMN `date_updated`            DATETIME NULL DEFAULT NULL AFTER `date_added`,
  ADD COLUMN `additional_emails_json`  JSON NULL AFTER `tags_json`,
  ADD COLUMN `followers_json`          JSON NULL AFTER `additional_emails_json`,
  ADD COLUMN `attributions_json`       JSON NULL AFTER `followers_json`,
  ADD COLUMN `custom_fields_json`      JSON NULL AFTER `attributions_json`,
  ADD INDEX `idx_ghl_contacts_location_id` (`location_id`),
  ADD INDEX `idx_ghl_contacts_date_updated` (`date_updated`);

CREATE TABLE IF NOT EXISTS `ghl_custom_fields` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `location_id` VARCHAR(100) NOT NULL,
  `field_id` VARCHAR(100) NOT NULL,
  `field_key` VARCHAR(255) NULL DEFAULT NULL,
  `model` VARCHAR(50) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `data_type` VARCHAR(100) NULL DEFAULT NULL,
  `placeholder` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL,
  `position` INT NULL DEFAULT NULL,
  `show_in_forms` TINYINT(1) NOT NULL DEFAULT 0,
  `parent_id` VARCHAR(100) NULL DEFAULT NULL,
  `object_key` VARCHAR(255) NULL DEFAULT NULL,
  `options_json` JSON NULL,
  `raw_json` JSON NULL,
  `date_added` DATETIME NULL DEFAULT NULL,
  `date_updated` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_ghl_custom_fields_location_field` (`location_id`, `field_id`),
  KEY `idx_ghl_custom_fields_field_key` (`field_key`),
  KEY `idx_ghl_custom_fields_model` (`model`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ghl_contact_custom_field_values` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `contact_id` VARCHAR(100) NOT NULL,
  `field_identity` VARCHAR(255) NOT NULL,
  `field_id` VARCHAR(100) NULL DEFAULT NULL,
  `field_key` VARCHAR(255) NULL DEFAULT NULL,
  `field_name` VARCHAR(255) NULL DEFAULT NULL,
  `value_text` TEXT NULL,
  `value_json` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_ghl_contact_field_value` (`contact_id`, `field_identity`),
  KEY `idx_ghl_contact_custom_field_values_field_id` (`field_id`),
  KEY `idx_ghl_contact_custom_field_values_field_key` (`field_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
