-- GHL (GoHighLevel) opportunities sync table
-- Stores opportunities fetched from GET https://services.leadconnectorhq.com/opportunities/search

CREATE TABLE IF NOT EXISTS `ghl_opportunities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `opportunity_id` VARCHAR(100) NOT NULL COMMENT 'GHL opportunity id',
  `location_id` VARCHAR(100) NULL DEFAULT NULL,
  `contact_id` VARCHAR(100) NULL DEFAULT NULL,
  `assigned_to` VARCHAR(100) NULL DEFAULT NULL COMMENT 'GHL user id',
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `monetary_value` DECIMAL(15,2) NULL DEFAULT NULL,
  `pipeline_id` VARCHAR(100) NULL DEFAULT NULL,
  `pipeline_stage_id` VARCHAR(100) NULL DEFAULT NULL,
  `pipeline_stage_uid` VARCHAR(100) NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  `source` VARCHAR(255) NULL DEFAULT NULL,
  `lost_reason_id` VARCHAR(100) NULL DEFAULT NULL,
  `contact_name` VARCHAR(255) NULL DEFAULT NULL,
  `company_name` VARCHAR(255) NULL DEFAULT NULL,
  `contact_email` VARCHAR(255) NULL DEFAULT NULL,
  `contact_phone` VARCHAR(50) NULL DEFAULT NULL,
  `last_status_change_at` DATETIME NULL DEFAULT NULL,
  `last_stage_change_at` DATETIME NULL DEFAULT NULL,
  `opportunity_created_at` DATETIME NULL DEFAULT NULL,
  `opportunity_updated_at` DATETIME NULL DEFAULT NULL,
  `custom_fields_json` JSON NULL,
  `followers_json` JSON NULL,
  `relations_json` JSON NULL,
  `contact_json` JSON NULL,
  `contact_tags_json` JSON NULL,
  `contact_score_json` JSON NULL,
  `sort_json` JSON NULL,
  `attributions_json` JSON NULL,
  `raw_json` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_opportunity_id` (`opportunity_id`),
  KEY `idx_location_id` (`location_id`),
  KEY `idx_contact_id` (`contact_id`),
  KEY `idx_assigned_to` (`assigned_to`),
  KEY `idx_pipeline_id` (`pipeline_id`),
  KEY `idx_pipeline_stage_id` (`pipeline_stage_id`),
  KEY `idx_status` (`status`),
  KEY `idx_opportunity_updated_at` (`opportunity_updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
